<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="fb_gm_removeLens" Id="{a652fa65-7059-4187-8597-894c14dd1d48}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fb_gm_removeLens
VAR_INPUT
	in_flg_run: BOOL;
END_VAR
VAR_OUTPUT
	out_flg_Done: BOOL;
END_VAR
VAR
	SFCInit: BOOL;
	trn_checkVacDone: BOOL;
	trn_rmoveLensThetaDone: BOOL;
	var_process: INT;
	trn_removeLensDone: BOOL;
	trn_removeLen_stocker_eject_Done : BOOL;
	trn_removeLen_stocker_fiber_Done : BOOL;
	trn_removeLen_measurement_eject_Done : BOOL;
	trn_removeLen_measurement_fiber_Done : BOOL;
	timer: TON;
	timer2: TON;
END_VAR

]]></Declaration>
    <Implementation>
      <SFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="SFCImplementationObject">
              <o n="Root" t="SFCSegment">
                <o n="ElementList" t="SFCElementList">
                  <l2 n="InnerList">
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Init"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">11L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">12L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">13L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">14L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"TRUE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">15L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">16L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">17L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">18L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Init_active_0"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">19L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">20L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">21L</v>
                          <v n="IdParent">10L</v>
                        </o>
                      </l2>
                      <v n="Id">10L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"Init__to__Step0"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"in_flg_run"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">131L</v>
                          <v n="IdParent">130L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">132L</v>
                          <v n="IdParent">130L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">133L</v>
                          <v n="IdParent">130L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">134L</v>
                          <v n="IdParent">130L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">135L</v>
                          <v n="IdParent">130L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">136L</v>
                          <v n="IdParent">130L</v>
                        </o>
                      </l2>
                      <v n="Id">130L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Step0"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">138L</v>
                          <v n="IdParent">137L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">139L</v>
                          <v n="IdParent">137L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">140L</v>
                          <v n="IdParent">137L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">141L</v>
                          <v n="IdParent">137L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">142L</v>
                          <v n="IdParent">137L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">143L</v>
                          <v n="IdParent">137L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">144L</v>
                          <v n="IdParent">137L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">145L</v>
                          <v n="IdParent">137L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">146L</v>
                          <v n="IdParent">137L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">147L</v>
                          <v n="IdParent">137L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">148L</v>
                          <v n="IdParent">137L</v>
                        </o>
                      </l2>
                      <v n="Id">137L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCBranch">
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" cet="SFCSegment">
                          <o>
                            <o n="ElementList" t="SFCElementList">
                              <l2 n="InnerList" cet="SFCTransition">
                                <o>
                                  <v n="VariableName">"Branch0__Step0__to__removeLen_stocker_eject"</v>
                                  <n n="EmbeddedTransition" />
                                  <l2 n="EmbeddedTransitionProperties" />
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"gvl_solv.ref_gm_ejctor.input.in_flg_sensVac = false"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">23L</v>
                                      <v n="IdParent">22L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">24L</v>
                                      <v n="IdParent">22L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">25L</v>
                                      <v n="IdParent">22L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">26L</v>
                                      <v n="IdParent">22L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">27L</v>
                                      <v n="IdParent">22L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">28L</v>
                                      <v n="IdParent">22L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">22L</v>
                                  <v n="IdParent">59L</v>
                                </o>
                              </l2>
                            </o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">60L</v>
                                <v n="IdParent">59L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">61L</v>
                                <v n="IdParent">59L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">62L</v>
                                <v n="IdParent">59L</v>
                              </o>
                            </l2>
                            <v n="Id">59L</v>
                            <v n="IdParent">54L</v>
                          </o>
                          <o>
                            <o n="ElementList" t="SFCElementList">
                              <l2 n="InnerList">
                                <o t="SFCTransition">
                                  <v n="VariableName">"Branch1__Step0__to__rmoveLensTheta"</v>
                                  <n n="EmbeddedTransition" />
                                  <l2 n="EmbeddedTransitionProperties" />
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"gvl_solv.ref_gm_ejctor.input.in_flg_sensVac = true"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">68L</v>
                                      <v n="IdParent">67L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">69L</v>
                                      <v n="IdParent">67L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">70L</v>
                                      <v n="IdParent">67L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">71L</v>
                                      <v n="IdParent">67L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">72L</v>
                                      <v n="IdParent">67L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">73L</v>
                                      <v n="IdParent">67L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">67L</v>
                                  <v n="IdParent">63L</v>
                                </o>
                                <o t="SFCStep">
                                  <n n="EmbeddedMainAction" />
                                  <n n="EmbeddedEntryAction" />
                                  <n n="EmbeddedExitAction" />
                                  <l2 n="EmbeddedMainActionProperties" />
                                  <l2 n="EmbeddedEntryActionProperties" />
                                  <l2 n="EmbeddedExitActionProperties" />
                                  <o n="ElementList" t="SFCElementList">
                                    <l2 n="InnerList" />
                                  </o>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"rmoveLensTheta"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">75L</v>
                                      <v n="IdParent">74L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">76L</v>
                                      <v n="IdParent">74L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">77L</v>
                                      <v n="IdParent">74L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">78L</v>
                                      <v n="IdParent">74L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">79L</v>
                                      <v n="IdParent">74L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">80L</v>
                                      <v n="IdParent">74L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">81L</v>
                                      <v n="IdParent">74L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">82L</v>
                                      <v n="IdParent">74L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"rmoveLensTheta_active"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">83L</v>
                                      <v n="IdParent">74L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">84L</v>
                                      <v n="IdParent">74L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">85L</v>
                                      <v n="IdParent">74L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">74L</v>
                                  <v n="IdParent">63L</v>
                                </o>
                                <o t="SFCTransition">
                                  <v n="VariableName">"rmoveLensTheta__to__removeLen_stocker_eject"</v>
                                  <n n="EmbeddedTransition" />
                                  <l2 n="EmbeddedTransitionProperties" />
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"trn_rmoveLensThetaDone"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">87L</v>
                                      <v n="IdParent">86L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">88L</v>
                                      <v n="IdParent">86L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">89L</v>
                                      <v n="IdParent">86L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">90L</v>
                                      <v n="IdParent">86L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">91L</v>
                                      <v n="IdParent">86L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">92L</v>
                                      <v n="IdParent">86L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">86L</v>
                                  <v n="IdParent">63L</v>
                                </o>
                              </l2>
                            </o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">64L</v>
                                <v n="IdParent">63L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">65L</v>
                                <v n="IdParent">63L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">66L</v>
                                <v n="IdParent">63L</v>
                              </o>
                            </l2>
                            <v n="Id">63L</v>
                            <v n="IdParent">54L</v>
                          </o>
                        </l2>
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Branch0"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">55L</v>
                          <v n="IdParent">54L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">56L</v>
                          <v n="IdParent">54L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">57L</v>
                          <v n="IdParent">54L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">58L</v>
                          <v n="IdParent">54L</v>
                        </o>
                      </l2>
                      <v n="Id">54L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"removeLen_stocker_eject"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">215L</v>
                          <v n="IdParent">214L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">216L</v>
                          <v n="IdParent">214L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">217L</v>
                          <v n="IdParent">214L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">218L</v>
                          <v n="IdParent">214L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">219L</v>
                          <v n="IdParent">214L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">220L</v>
                          <v n="IdParent">214L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">221L</v>
                          <v n="IdParent">214L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">222L</v>
                          <v n="IdParent">214L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"removeLen_stocker_eject_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">223L</v>
                          <v n="IdParent">214L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">224L</v>
                          <v n="IdParent">214L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">225L</v>
                          <v n="IdParent">214L</v>
                        </o>
                      </l2>
                      <v n="Id">214L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"removeLen_stocker_eject__to__removeLen_stocker_fiber"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"trn_removeLen_stocker_eject_Done"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">208L</v>
                          <v n="IdParent">207L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">209L</v>
                          <v n="IdParent">207L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">210L</v>
                          <v n="IdParent">207L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">211L</v>
                          <v n="IdParent">207L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">212L</v>
                          <v n="IdParent">207L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">213L</v>
                          <v n="IdParent">207L</v>
                        </o>
                      </l2>
                      <v n="Id">207L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"removeLen_stocker_fiber"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">196L</v>
                          <v n="IdParent">195L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">197L</v>
                          <v n="IdParent">195L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">198L</v>
                          <v n="IdParent">195L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">199L</v>
                          <v n="IdParent">195L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">200L</v>
                          <v n="IdParent">195L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">201L</v>
                          <v n="IdParent">195L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">202L</v>
                          <v n="IdParent">195L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">203L</v>
                          <v n="IdParent">195L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">204L</v>
                          <v n="IdParent">195L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">205L</v>
                          <v n="IdParent">195L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">206L</v>
                          <v n="IdParent">195L</v>
                        </o>
                      </l2>
                      <v n="Id">195L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"removeLen_stocker_fiber__to__removeLen_measurement_eject"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"trn_removeLen_stocker_fiber_Done"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">189L</v>
                          <v n="IdParent">188L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">190L</v>
                          <v n="IdParent">188L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">191L</v>
                          <v n="IdParent">188L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">192L</v>
                          <v n="IdParent">188L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">193L</v>
                          <v n="IdParent">188L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">194L</v>
                          <v n="IdParent">188L</v>
                        </o>
                      </l2>
                      <v n="Id">188L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"removeLen_measurement_eject"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">177L</v>
                          <v n="IdParent">176L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">178L</v>
                          <v n="IdParent">176L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">179L</v>
                          <v n="IdParent">176L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">180L</v>
                          <v n="IdParent">176L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">181L</v>
                          <v n="IdParent">176L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">182L</v>
                          <v n="IdParent">176L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">183L</v>
                          <v n="IdParent">176L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">184L</v>
                          <v n="IdParent">176L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">185L</v>
                          <v n="IdParent">176L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">186L</v>
                          <v n="IdParent">176L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">187L</v>
                          <v n="IdParent">176L</v>
                        </o>
                      </l2>
                      <v n="Id">176L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"removeLen_measurement_eject__to__removeLen_measurement_fiber"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"trn_removeLen_measurement_eject_Done"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">232L</v>
                          <v n="IdParent">231L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">233L</v>
                          <v n="IdParent">231L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">234L</v>
                          <v n="IdParent">231L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">235L</v>
                          <v n="IdParent">231L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">236L</v>
                          <v n="IdParent">231L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">237L</v>
                          <v n="IdParent">231L</v>
                        </o>
                      </l2>
                      <v n="Id">231L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"removeLen_measurement_fiber"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">239L</v>
                          <v n="IdParent">238L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">240L</v>
                          <v n="IdParent">238L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">241L</v>
                          <v n="IdParent">238L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">242L</v>
                          <v n="IdParent">238L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">243L</v>
                          <v n="IdParent">238L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">244L</v>
                          <v n="IdParent">238L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">245L</v>
                          <v n="IdParent">238L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">246L</v>
                          <v n="IdParent">238L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">247L</v>
                          <v n="IdParent">238L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">248L</v>
                          <v n="IdParent">238L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">249L</v>
                          <v n="IdParent">238L</v>
                        </o>
                      </l2>
                      <v n="Id">238L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"removeLen_measurement_fiber__to__removeLens"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"trn_removeLen_measurement_fiber_Done"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">170L</v>
                          <v n="IdParent">169L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">171L</v>
                          <v n="IdParent">169L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">172L</v>
                          <v n="IdParent">169L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">173L</v>
                          <v n="IdParent">169L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">174L</v>
                          <v n="IdParent">169L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">175L</v>
                          <v n="IdParent">169L</v>
                        </o>
                      </l2>
                      <v n="Id">169L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"removeLens"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">94L</v>
                          <v n="IdParent">93L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">95L</v>
                          <v n="IdParent">93L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">96L</v>
                          <v n="IdParent">93L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">97L</v>
                          <v n="IdParent">93L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">98L</v>
                          <v n="IdParent">93L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">99L</v>
                          <v n="IdParent">93L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">100L</v>
                          <v n="IdParent">93L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">101L</v>
                          <v n="IdParent">93L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"removeLens_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">102L</v>
                          <v n="IdParent">93L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">103L</v>
                          <v n="IdParent">93L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">104L</v>
                          <v n="IdParent">93L</v>
                        </o>
                      </l2>
                      <v n="Id">93L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"removeLens__to__Init"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"trn_removeLensDone"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">113L</v>
                          <v n="IdParent">112L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">114L</v>
                          <v n="IdParent">112L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">115L</v>
                          <v n="IdParent">112L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">116L</v>
                          <v n="IdParent">112L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">117L</v>
                          <v n="IdParent">112L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">118L</v>
                          <v n="IdParent">112L</v>
                        </o>
                      </l2>
                      <v n="Id">112L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCJump">
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Init"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">30L</v>
                          <v n="IdParent">29L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">31L</v>
                          <v n="IdParent">29L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">32L</v>
                          <v n="IdParent">29L</v>
                        </o>
                      </l2>
                      <v n="Id">29L</v>
                      <v n="IdParent">9L</v>
                    </o>
                  </l2>
                </o>
                <l2 n="Attributes" cet="SFCAttribute">
                  <o>
                    <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                    <o n="Value" t="StringValue">
                      <v n="Value">""</v>
                      <v n="DefaultValue">""</v>
                    </o>
                    <v n="Id">149L</v>
                    <v n="IdParent">9L</v>
                  </o>
                  <o>
                    <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                    <o n="Value" t="StringValue">
                      <v n="Value">""</v>
                      <v n="DefaultValue">""</v>
                    </o>
                    <v n="Id">150L</v>
                    <v n="IdParent">9L</v>
                  </o>
                  <o>
                    <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                    <o n="Value" t="BoolValue">
                      <v n="Value">"FALSE"</v>
                      <v n="DefaultValue">"FALSE"</v>
                    </o>
                    <v n="Id">151L</v>
                    <v n="IdParent">9L</v>
                  </o>
                </l2>
                <v n="Id">9L</v>
                <v n="IdParent">-1L</v>
              </o>
              <d2 n="Categories" ckt="Guid" cvt="SFCAttributeCategory">
                <v>1c5c6e05-2bb7-4258-bcee-fd16a540c63c</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Identifier">"Specific"</v>
                  <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="Description">"属性型固有プロパティ"</v>
                </o>
                <v>20f0fc67-978d-438b-979f-eef294f34ee4</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Identifier">"Actions"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"アクション定義"</v>
                </o>
                <v>6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Identifier">"Common"</v>
                  <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="Description">"共通プロパティ"</v>
                </o>
                <v>d336ba06-8a67-4e6b-9697-50f83ba6bdde</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Identifier">"Times"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"時間定義"</v>
                </o>
              </d2>
              <d2 n="Attributes" ckt="Guid" cvt="SFCAttributeDescription">
                <v>01580b27-6378-448b-8ecb-0e4b795b58d6</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">true</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                  <v n="Identifier">"Exclude"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"この要素をビルドから除外"</v>
                </o>
                <v>23bdaa98-72ec-41f7-817b-9dede5697086</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                  <v n="Identifier">"Parallel"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"分岐を並列モードに設定します"</v>
                </o>
                <v>38391c6d-6d4a-42f8-8ee7-9f45e5adafa8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                  <v n="Identifier">"Name"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"要素名"</v>
                </o>
                <v>62e1754b-7629-4e63-9cec-10ae0c536f1f</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                  <v n="Identifier">"Duplication"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"ステップ アクションまたは要素のある遷移の実装をコピーします。そうでない場合、参照を既存の実装にコピーします。"</v>
                </o>
                <v>6844a48e-46c2-4cc8-a185-a478f3b99cc0</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                  <v n="Identifier">"InitStep"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"初期ステップとしてステップを設定します"</v>
                </o>
                <v>700a583f-b4d4-43e4-8c14-629c7cd3bec8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                  <v n="Identifier">"MainAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"ステップがアクティブの場合に呼び出されるアクション名"</v>
                </o>
                <v>7d894980-aeea-405c-a0f6-e2b26429c58f</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">true</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                  <v n="Identifier">"Comment"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"要素のコメント"</v>
                </o>
                <v>8294df19-5962-4dee-a874-1051dabb0e3e</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                  <v n="Identifier">"Monitoring"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"トランジション監視設定を示しています。"</v>
                </o>
                <v>a2621e18-7de3-4ea6-ae6d-89e9e0b7befd</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                  <v n="Identifier">"ExitAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"ステップが非アクティブの場合に呼び出されるアクション名"</v>
                </o>
                <v>a6b08bd8-b696-47e3-9cbf-7408b61c9ff8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                  <v n="Identifier">"EntryAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"ステップがアクティブの場合に呼び出されるアクション名"</v>
                </o>
                <v>b693554c-1b01-4a8d-afde-9e3a46f7465d</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                  <v n="Identifier">"MaxTime"</v>
                  <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Description">"最大アクティブ時間をステップに定義します"</v>
                </o>
                <v>bc882c11-1e91-4dd8-a6b8-2075724ed18b</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                  <v n="Identifier">"Symbol"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"要素のシンボル コンフィグレーション設定"</v>
                </o>
                <v>cacf1a68-236e-47c2-b7b1-1cf9199718cb</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                  <v n="Identifier">"MinTime"</v>
                  <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Description">"最小アクティブ時間をステップに定義します"</v>
                </o>
                <v>e174fc0d-80b0-4a9e-a530-ca239c249a50</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                  <v n="Identifier">"Qualifier"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"アクション関連付けの修飾子"</v>
                </o>
              </d2>
              <d2 n="EnumTemplates" ckt="Guid" cvt="EnumValueTemplate">
                <v>6ecff51c-9b8f-4338-aab0-67c2b31b07e9</v>
                <o>
                  <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                  <l n="Values" t="ArrayList" cet="EnumEntry">
                    <o>
                      <v n="Identifier">"None"</v>
                      <v n="Value">0L</v>
                      <v n="Key">"None"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Variable"</v>
                      <v n="Value">1L</v>
                      <v n="Key">"Variable"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Call"</v>
                      <v n="Value">2L</v>
                      <v n="Key">"Call"</v>
                    </o>
                  </l>
                  <v n="BaseType">"INT"</v>
                </o>
                <v>79a4fdd5-c859-4de4-aa8d-c03372c880c2</v>
                <o>
                  <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                  <l n="Values" t="ArrayList" cet="EnumEntry">
                    <o>
                      <v n="Identifier">"Unspecified"</v>
                      <v n="Value">0L</v>
                      <v n="Key">"Unspecified"</v>
                    </o>
                    <o>
                      <v n="Identifier">"None"</v>
                      <v n="Value">1L</v>
                      <v n="Key">"None"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Read"</v>
                      <v n="Value">2L</v>
                      <v n="Key">"Read"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Write"</v>
                      <v n="Value">3L</v>
                      <v n="Key">"Write"</v>
                    </o>
                    <o>
                      <v n="Identifier">"ReadWrite"</v>
                      <v n="Value">4L</v>
                      <v n="Key">"ReadWrite"</v>
                    </o>
                  </l>
                  <v n="BaseType">"INT"</v>
                </o>
              </d2>
            </o>
          </Data>
          <TypeList>
            <Type n="ArrayList">System.Collections.ArrayList</Type>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoolValue">{89e1c7bb-c9f8-4be3-b8a7-019cdbb9f7e8}</Type>
            <Type n="EnumEntry">{4185e6da-1717-44c9-b705-102861764479}</Type>
            <Type n="EnumValue">{4dd7572b-4b9d-4d35-963e-6a34a4aaa5c1}</Type>
            <Type n="EnumValueTemplate">{d6bfe4f0-d62f-4b5f-9f95-2bbeb1950e28}</Type>
            <Type n="Guid">System.Guid</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="SFCAttribute">{21f3f16e-04fa-4637-b6b7-d84e4192e99f}</Type>
            <Type n="SFCAttributeCategory">{679adacf-f2a4-4167-a3f7-d21cfc5d451f}</Type>
            <Type n="SFCAttributeDescription">{d851789d-af2c-4990-9d48-a7bdc9181773}</Type>
            <Type n="SFCBranch">{e221b778-bb8f-44ba-8a6a-f796287d4e62}</Type>
            <Type n="SFCElementList">{587d6556-cfe6-4e76-9cc9-fc0daf0c8c29}</Type>
            <Type n="SFCImplementationObject">{74f81948-1328-492c-b6c1-a9ea72048b28}</Type>
            <Type n="SFCJump">{7e39ac27-154f-419a-a255-6a6cf37d5ed0}</Type>
            <Type n="SFCSegment">{f1db7f6f-4774-46a6-ad9b-a94414f875fc}</Type>
            <Type n="SFCStep">{86ee92a2-d863-4136-be27-82b36d84211c}</Type>
            <Type n="SFCTransition">{4ecb29e8-a90a-4646-84ac-2ff54215ab29}</Type>
            <Type n="String">System.String</Type>
            <Type n="StringValue">{778c8bac-3fa0-41e1-99d3-2b628d12d3e5}</Type>
          </TypeList>
        </XmlArchive>
      </SFC>
    </Implementation>
    <Action Name="Init_active" Id="{89c4f83a-a694-4f99-ab4b-138e7e567033}">
      <Implementation>
        <ST><![CDATA[trn_removeLensDOne := false;]]></ST>
      </Implementation>
    </Action>
    <Action Name="Init_active_0" Id="{a0514581-c5e7-491a-b4b1-406e48d7cff9}">
      <Implementation>
        <ST><![CDATA[out_flg_done := false;]]></ST>
      </Implementation>
    </Action>
    <Property Name="p_Init" Id="{ed900328-9a15-4edc-b486-c4dfbede0b7f}">
      <Declaration><![CDATA[PROPERTY p_Init : BOOL]]></Declaration>
      <Get Name="Get" Id="{5f4c62d5-a4e7-4781-a31e-30e17f86c1cb}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[p_Init := THIS^.SFCInit;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{0f71ef2c-6bc4-448b-9e0a-6dc10fb66dbd}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[THIS^.SFCInit := p_Init;]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Action Name="removeLen_stocker_eject_active" Id="{557eafa1-9040-433e-a5c7-b763c076be3f}">
      <Implementation>
        <ST><![CDATA[IF removeLen_stocker_eject._x AND removeLen_stocker_eject.x = FALSE THEN
	trn_removeLensDone := FALSE;
	timer.IN := FALSE;
	timer2.IN := FALSE;
	gvl_elecylinder.fbi_gm_axisPickUp.in_flg_run := FALSE;
	gvl_elecylinder.fbi_gm_axisPickUp.in_var_moveMode := eP_eleMoveMode.eleB;
	gvl_solv.fbi_gm_ejector.in_flg_run := FALSE;
	gvl_solv.fbi_gm_ejector.in_var_vacMode := eP_ejeVacMode.halt;
	gvl_axis.ref_r.Execute := FALSE;
	gvl_solv.fbi_gm_chuck.in_var_moveMode := eP_svMoveMode.svB;
	gvl_solv.fbi_gm_chuck.in_flg_run := FALSE;
	gvl_solv.fbi_gm_push.in_var_moveMode := eP_svMoveMode.svB;
	gvl_solv.fbi_gm_push.in_flg_run := FALSE;
	gvl_axis.ref_r.Position := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.gm_rotary.pickUp;
	var_process := 0;
ELSIF removeLen_stocker_eject._x AND removeLen_stocker_eject.x THEN
	CASE var_process OF
		0:
			IF gvl_io.flg_gm_fiberSens THEN
				var_process := 1;
			ELSE
				var_process := 100;
			END_IF
		1:
			
			
		
		
		100:
			trn_removeLensDone := TRUE;

	END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="removeLens_active" Id="{1ea01717-d15e-4817-bcea-abd2ac008929}">
      <Implementation>
        <ST><![CDATA[IF removeLens._x AND removeLens.x = FALSE THEN
	trn_removeLensDone := FALSE;
	timer.IN := FALSE;
	timer2.IN := FALSE;
	gvl_elecylinder.fbi_gm_axisPickUp.in_flg_run := FALSE;
	gvl_elecylinder.fbi_gm_axisPickUp.in_var_moveMode := eP_eleMoveMode.eleB;
	gvl_solv.fbi_gm_ejector.in_flg_run := FALSE;
	gvl_solv.fbi_gm_ejector.in_var_vacMode := eP_ejeVacMode.halt;
	gvl_axis.ref_r.Execute := FALSE;
	gvl_solv.fbi_gm_chuck.in_var_moveMode := eP_svMoveMode.svB;
	gvl_solv.fbi_gm_chuck.in_flg_run := FALSE;
	gvl_solv.fbi_gm_push.in_var_moveMode := eP_svMoveMode.svB;
	gvl_solv.fbi_gm_push.in_flg_run := FALSE;
	gvl_axis.ref_r.Position := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.gm_rotary.pickUp;
	var_process := 0;
ELSIF removeLens._x AND removeLens.x THEN
	CASE var_process OF
		0:
			IF gvl_io.flg_gm_fiberSens THEN
				//gvl_solv.fbi_gm_chuck.in_flg_run := TRUE;
				gvl_solv.fbi_gm_ejector.in_var_vacMode := eP_ejeVacMode.break;
				gvl_solv.fbi_gm_ejector.in_flg_run := TRUE;
				var_process := 15;
			ELSE
				gvl_solv.fbi_gm_ejector.in_var_vacMode := eP_ejeVacMode.break;
				gvl_solv.fbi_gm_ejector.in_flg_run := TRUE;
				var_process := 15;
			END_IF
		1:
			IF gvl_solv.fbi_gm_chuck.out_flg_Done THEN
				gvl_solv.fbi_gm_chuck.in_var_moveMode := eP_svMoveMode.svA;
				gvl_solv.fbi_gm_chuck.in_flg_run := FALSE;
				gvl_solv.fbi_gm_push.in_flg_run := TRUE;
				var_process := 2;
			END_IF
		2:
			IF gvl_solv.fbi_gm_push.out_flg_Done THEN
				gvl_solv.fbi_gm_push.in_var_moveMode := eP_svMoveMode.svA;
				gvl_solv.fbi_gm_push.in_flg_run := FALSE;
				var_process := 3;
			END_IF	
		3:
			gvl_axis.ref_r.Execute := TRUE;
			var_process := 4;
		4:
			IF gvl_axis.ref_r.Done THEN
				gvl_axis.ref_r.Execute := FALSE;
				var_process := 5;
			END_IF
		5:	
			gvl_solv.fbi_gm_ejector.in_flg_run := TRUE;
			gvl_elecylinder.fbi_gm_axisPickUp.in_flg_run := TRUE;
			var_process := 6;
		6:
			IF gvl_elecylinder.fbi_gm_axisPickUp.out_flg_Done THEN
				timer.IN := TRUE;
				gvl_elecylinder.fbi_gm_axisPickUp.in_flg_run := FALSE;
				var_process := 7;
			END_IF
		7:
			IF 	timer.Q THEN
				gvl_elecylinder.fbi_gm_axisPickUp.in_var_moveMode := eP_eleMoveMode.eleA;
				gvl_elecylinder.fbi_gm_axisPickUp.in_flg_run := FALSE;
				var_process := 8;
			END_IF
		8:
			gvl_solv.fbi_gm_chuck.in_flg_run := TRUE;
			gvl_solv.fbi_gm_push.in_flg_run := TRUE;
			var_process := 9;
		9:
			timer2.IN := TRUE;
			IF timer2.Q THEN
				var_process := 10;
			END_IF
			
		10:
			gvl_elecylinder.fbi_gm_axisPickUp.in_flg_run := TRUE;
			gvl_axis.ref_r.Position := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.gm_rotary.remove;
			var_process := 11;
		11:
			IF gvl_elecylinder.fbi_gm_axisPickUp.out_flg_Done THEN
				gvl_axis.ref_r.Execute := TRUE;
				gvl_solv.fbi_gm_ejector.in_flg_run := FALSE;
				gvl_solv.fbi_gm_ejector.in_var_vacMode := eP_ejeVacMode.break;
				var_process := 12;
			END_IF
		12:
			IF gvl_axis.ref_r.Done THEN
				gvl_axis.ref_r.Execute := FALSE;
				gvl_solv.fbi_gm_ejector.in_flg_run := TRUE;
				var_process := 13;
			END_IF
		13:
			IF gvl_solv.fbi_gm_ejector.out_flg_Done THEN
				gvl_axis.ref_r.Position := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.gm_rotary.origin;
				gvl_axis.ref_r.Execute := TRUE;
				var_process := 14;
			END_IF
		14:
			IF gvl_axis.ref_r.Done THEN
				gvl_axis.ref_r.Execute := FALSE;
				var_process := 15;
			END_IF
		15:
			gvl_solv.fbi_gm_ejector.in_flg_run := FALSE;
			out_flg_Done := TRUE;
			trn_removeLensDone := TRUE;
			
			
			
	END_CASE
timer(IN:= , PT:=T#0.5S , Q=> , ET=> );
timer2(IN:= , PT:=T#0.2S , Q=> , ET=> );
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="rmoveLensTheta_active" Id="{5b3b94fd-3952-4c3f-998a-e4be43ed7eea}">
      <Implementation>
        <ST><![CDATA[IF rmoveLensTheta._x AND rmoveLensTheta.x = FALSE THEN
	var_process := 0;
	trn_rmoveLensThetaDone := FALSE;
	gvl_axis.ref_r.Execute := FALSE;
	gvl_solv.fbi_gm_ejector.in_flg_run := FALSE;
	gvl_solv.fbi_gm_ejector.in_var_vacMode := eP_ejeVacMode.break;
	gvl_axis.ref_r.Position := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.gm_rotary.remove;
ELSIF rmoveLensTheta._x AND rmoveLensTheta.x THEN
	CASE var_process OF
		0:
			gvl_axis.ref_r.Execute := TRUE;
			var_process := 1;
		1:
			IF gvl_axis.ref_r.Done THEN
				gvl_solv.fbi_gm_ejector.in_flg_run := TRUE;
				var_process := 2;
			END_IF
		2:
			IF gvl_solv.fbi_gm_ejector.out_flg_Done THEN
				var_process := 3;
			END_IF
		3:	
			gvl_axis.ref_r.Position := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.gm_rotary.pickUp;
			gvl_axis.ref_r.Execute := FALSE;
			var_process := 4;
		4:
			gvl_axis.ref_r.Execute := TRUE;
			var_process := 5;
		5:
			IF gvl_axis.ref_r.Done THEN
				trn_rmoveLensThetaDone := TRUE;
			END_IF
	END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="SFCProperty">
            <n n="SFCErrorAnalyzation" />
            <n n="SFCErrorAnalyzationTable" />
            <v n="Title">"IecSfc"</v>
            <v n="Company">"System"</v>
            <v n="Version">"3.4.2.0"</v>
            <v n="Namespace">""</v>
            <d2 n="Flags" ckt="Flags" cvt="SFCPropertyFlagData">
              <v>EnableLimit</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Init</v>
              <o>
                <v n="Use">true</v>
                <v n="Declare">true</v>
              </o>
              <v>Reset</v>
              <o>
                <v n="Use">true</v>
                <v n="Declare">true</v>
              </o>
              <v>QuitError</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Pause</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Error</v>
              <o>
                <v n="Use">true</v>
                <v n="Declare">true</v>
              </o>
              <v>Trans</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>ErrorStep</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>ErrorPOU</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>CurrentStep</v>
              <o>
                <v n="Use">true</v>
                <v n="Declare">true</v>
              </o>
              <v>Tip</v>
              <o>
                <v n="Use">true</v>
                <v n="Declare">true</v>
              </o>
              <v>TipMode</v>
              <o>
                <v n="Use">true</v>
                <v n="Declare">true</v>
              </o>
              <v>SFCErrorAnalyzation</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>SFCErrorAnalyzationTable</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
            </d2>
            <v n="CalcActiveTransOnly">false</v>
            <v n="UseDefaults">true</v>
          </o>
        </Data>
        <TypeList>
          <Type n="Boolean">System.Boolean</Type>
          <Type n="Flags">{27d8150b-ef58-4fff-8da1-1f7dd5f9ea51}</Type>
          <Type n="SFCProperty">{58548d2c-f1b1-453d-9195-66c94e2a3ae0}</Type>
          <Type n="SFCPropertyFlagData">{24565a38-6368-4874-ab9a-0ef7ec269521}</Type>
          <Type n="String">System.String</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
    <LineIds Name="fb_gm_removeLens.Init_active">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="fb_gm_removeLens.Init_active_0">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="fb_gm_removeLens.p_Init.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="fb_gm_removeLens.p_Init.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="fb_gm_removeLens.removeLen_stocker_eject_active">
      <LineId Id="2" Count="22" />
      <LineId Id="29" Count="0" />
      <LineId Id="33" Count="0" />
      <LineId Id="32" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="30" Count="0" />
      <LineId Id="25" Count="3" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="fb_gm_removeLens.removeLens_active">
      <LineId Id="2" Count="112" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="fb_gm_removeLens.rmoveLensTheta_active">
      <LineId Id="2" Count="32" />
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>