<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="fb_auto" Id="{45b3f956-88f7-486e-97f8-ae993956690a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fb_auto
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	SFCInit: BOOL;
	trn_paramInitDone: BOOL;
	trn_moveToHomeDone: BOOL;
	trn_removeLensDone: BOOL;
	fbi_paramInit: fb_paramInit;
	var_process: INT;
	flg_tranHomeDone: BOOL;
	flg_sampleHomeDone: BOOL;
	flg_trayHomeDone: BOOL;
	flg_chuckHomeDone: BOOL;
	flg_axisHomeDone: BOOL;
	fbi_lensTranport: fb_lensTranport;
	fbi_palletizeing: fb_palletizeing;
	fbi_gm_measurementModule: fb_gm_measurementModule;
	fbi_gm_transport: fb_gm_transport;
	flg_pushHomeDone: BOOL;
	flg_rotaryHomeDone: BOOL;
	trn_measurementSystemHomeDone: BOOL;
	fbi_debuger : fb_debuger;
	fbi_gateLengthList: fb_gateLengthList;
	fbi_dataSampling: fb_dataSampling;
	timer: TON;
	timer2: TON;
	fbi_gm_removeLens: fb_gm_removeLens;
END_VAR
]]></Declaration>
    <Implementation>
      <SFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="SFCImplementationObject">
              <o n="Root" t="SFCSegment">
                <o n="ElementList" t="SFCElementList">
                  <l2 n="InnerList">
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Init"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">11L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">12L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">13L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">14L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"TRUE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">15L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">16L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">17L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">18L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">19L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">20L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">21L</v>
                          <v n="IdParent">10L</v>
                        </o>
                      </l2>
                      <v n="Id">10L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"Init__to__paramInit"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"TRUE"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">23L</v>
                          <v n="IdParent">22L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">24L</v>
                          <v n="IdParent">22L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">25L</v>
                          <v n="IdParent">22L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">26L</v>
                          <v n="IdParent">22L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">27L</v>
                          <v n="IdParent">22L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">28L</v>
                          <v n="IdParent">22L</v>
                        </o>
                      </l2>
                      <v n="Id">22L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"paramInit"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">34L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">35L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">36L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">37L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">38L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">39L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">40L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">41L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"paramInit_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">42L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">43L</v>
                          <v n="IdParent">33L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">44L</v>
                          <v n="IdParent">33L</v>
                        </o>
                      </l2>
                      <v n="Id">33L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"paramInit__to__Step1"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"trn_paramInitDone"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">46L</v>
                          <v n="IdParent">45L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">47L</v>
                          <v n="IdParent">45L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">48L</v>
                          <v n="IdParent">45L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">49L</v>
                          <v n="IdParent">45L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">50L</v>
                          <v n="IdParent">45L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">51L</v>
                          <v n="IdParent">45L</v>
                        </o>
                      </l2>
                      <v n="Id">45L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Step1"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">230L</v>
                          <v n="IdParent">229L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">231L</v>
                          <v n="IdParent">229L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">232L</v>
                          <v n="IdParent">229L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">233L</v>
                          <v n="IdParent">229L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">234L</v>
                          <v n="IdParent">229L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">235L</v>
                          <v n="IdParent">229L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">236L</v>
                          <v n="IdParent">229L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">237L</v>
                          <v n="IdParent">229L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">238L</v>
                          <v n="IdParent">229L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">239L</v>
                          <v n="IdParent">229L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">240L</v>
                          <v n="IdParent">229L</v>
                        </o>
                      </l2>
                      <v n="Id">229L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCBranch">
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" cet="SFCSegment">
                          <o>
                            <o n="ElementList" t="SFCElementList">
                              <l2 n="InnerList">
                                <o t="SFCTransition">
                                  <v n="VariableName">"Branch0__Step1__to__measurementSystemHome"</v>
                                  <n n="EmbeddedTransition" />
                                  <l2 n="EmbeddedTransitionProperties" />
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"gvl_visu.flg_btn_usingMeasurementSystem = True"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">242L</v>
                                      <v n="IdParent">241L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">243L</v>
                                      <v n="IdParent">241L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">244L</v>
                                      <v n="IdParent">241L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">245L</v>
                                      <v n="IdParent">241L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">246L</v>
                                      <v n="IdParent">241L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">247L</v>
                                      <v n="IdParent">241L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">241L</v>
                                  <v n="IdParent">188L</v>
                                </o>
                                <o t="SFCStep">
                                  <n n="EmbeddedMainAction" />
                                  <n n="EmbeddedEntryAction" />
                                  <n n="EmbeddedExitAction" />
                                  <l2 n="EmbeddedMainActionProperties" />
                                  <l2 n="EmbeddedEntryActionProperties" />
                                  <l2 n="EmbeddedExitActionProperties" />
                                  <o n="ElementList" t="SFCElementList">
                                    <l2 n="InnerList" />
                                  </o>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"measurementSystemHome"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">137L</v>
                                      <v n="IdParent">136L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">138L</v>
                                      <v n="IdParent">136L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">139L</v>
                                      <v n="IdParent">136L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">140L</v>
                                      <v n="IdParent">136L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">141L</v>
                                      <v n="IdParent">136L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">142L</v>
                                      <v n="IdParent">136L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">143L</v>
                                      <v n="IdParent">136L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">144L</v>
                                      <v n="IdParent">136L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"measurementSystemHome_active"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">145L</v>
                                      <v n="IdParent">136L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">146L</v>
                                      <v n="IdParent">136L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">147L</v>
                                      <v n="IdParent">136L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">136L</v>
                                  <v n="IdParent">188L</v>
                                </o>
                                <o t="SFCTransition">
                                  <v n="VariableName">"measurementSystemHome__to__moveToHome"</v>
                                  <n n="EmbeddedTransition" />
                                  <l2 n="EmbeddedTransitionProperties" />
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"trn_measurementSystemHomeDone"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">223L</v>
                                      <v n="IdParent">222L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">224L</v>
                                      <v n="IdParent">222L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">225L</v>
                                      <v n="IdParent">222L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">226L</v>
                                      <v n="IdParent">222L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">227L</v>
                                      <v n="IdParent">222L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">228L</v>
                                      <v n="IdParent">222L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">222L</v>
                                  <v n="IdParent">188L</v>
                                </o>
                              </l2>
                            </o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">189L</v>
                                <v n="IdParent">188L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">190L</v>
                                <v n="IdParent">188L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">191L</v>
                                <v n="IdParent">188L</v>
                              </o>
                            </l2>
                            <v n="Id">188L</v>
                            <v n="IdParent">183L</v>
                          </o>
                          <o>
                            <o n="ElementList" t="SFCElementList">
                              <l2 n="InnerList" cet="SFCTransition">
                                <o>
                                  <v n="VariableName">"Branch1__Step1__to__moveToHome"</v>
                                  <n n="EmbeddedTransition" />
                                  <l2 n="EmbeddedTransitionProperties" />
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"gvl_visu.flg_btn_usingMeasurementSystem = false"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">209L</v>
                                      <v n="IdParent">208L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">210L</v>
                                      <v n="IdParent">208L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">211L</v>
                                      <v n="IdParent">208L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">212L</v>
                                      <v n="IdParent">208L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">213L</v>
                                      <v n="IdParent">208L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">214L</v>
                                      <v n="IdParent">208L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">208L</v>
                                  <v n="IdParent">192L</v>
                                </o>
                              </l2>
                            </o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">193L</v>
                                <v n="IdParent">192L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">194L</v>
                                <v n="IdParent">192L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">195L</v>
                                <v n="IdParent">192L</v>
                              </o>
                            </l2>
                            <v n="Id">192L</v>
                            <v n="IdParent">183L</v>
                          </o>
                        </l2>
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Branch0"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">184L</v>
                          <v n="IdParent">183L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">185L</v>
                          <v n="IdParent">183L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">186L</v>
                          <v n="IdParent">183L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">187L</v>
                          <v n="IdParent">183L</v>
                        </o>
                      </l2>
                      <v n="Id">183L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"moveToHome"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">53L</v>
                          <v n="IdParent">52L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">54L</v>
                          <v n="IdParent">52L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">55L</v>
                          <v n="IdParent">52L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">56L</v>
                          <v n="IdParent">52L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">57L</v>
                          <v n="IdParent">52L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">58L</v>
                          <v n="IdParent">52L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">59L</v>
                          <v n="IdParent">52L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">60L</v>
                          <v n="IdParent">52L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"moveToHome_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">61L</v>
                          <v n="IdParent">52L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">62L</v>
                          <v n="IdParent">52L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">63L</v>
                          <v n="IdParent">52L</v>
                        </o>
                      </l2>
                      <v n="Id">52L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"moveToHome__to__removeLens"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"trn_moveToHomeDone"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">65L</v>
                          <v n="IdParent">64L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">66L</v>
                          <v n="IdParent">64L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">67L</v>
                          <v n="IdParent">64L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">68L</v>
                          <v n="IdParent">64L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">69L</v>
                          <v n="IdParent">64L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">70L</v>
                          <v n="IdParent">64L</v>
                        </o>
                      </l2>
                      <v n="Id">64L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"removeLens"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">76L</v>
                          <v n="IdParent">75L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">77L</v>
                          <v n="IdParent">75L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">78L</v>
                          <v n="IdParent">75L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">79L</v>
                          <v n="IdParent">75L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">80L</v>
                          <v n="IdParent">75L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">81L</v>
                          <v n="IdParent">75L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">82L</v>
                          <v n="IdParent">75L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">83L</v>
                          <v n="IdParent">75L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"removeLens_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">84L</v>
                          <v n="IdParent">75L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">85L</v>
                          <v n="IdParent">75L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">86L</v>
                          <v n="IdParent">75L</v>
                        </o>
                      </l2>
                      <v n="Id">75L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"removeLens__to__autoRun"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"trn_removeLensDone"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">88L</v>
                          <v n="IdParent">87L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">89L</v>
                          <v n="IdParent">87L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">90L</v>
                          <v n="IdParent">87L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">91L</v>
                          <v n="IdParent">87L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">92L</v>
                          <v n="IdParent">87L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">93L</v>
                          <v n="IdParent">87L</v>
                        </o>
                      </l2>
                      <v n="Id">87L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"autoRun"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">97L</v>
                          <v n="IdParent">96L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">98L</v>
                          <v n="IdParent">96L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">99L</v>
                          <v n="IdParent">96L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">100L</v>
                          <v n="IdParent">96L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">101L</v>
                          <v n="IdParent">96L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">102L</v>
                          <v n="IdParent">96L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">103L</v>
                          <v n="IdParent">96L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">104L</v>
                          <v n="IdParent">96L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"autoRun_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">105L</v>
                          <v n="IdParent">96L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">106L</v>
                          <v n="IdParent">96L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">107L</v>
                          <v n="IdParent">96L</v>
                        </o>
                      </l2>
                      <v n="Id">96L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"autoRun__to__Init"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"false"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">109L</v>
                          <v n="IdParent">108L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">110L</v>
                          <v n="IdParent">108L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">111L</v>
                          <v n="IdParent">108L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">112L</v>
                          <v n="IdParent">108L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">113L</v>
                          <v n="IdParent">108L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">114L</v>
                          <v n="IdParent">108L</v>
                        </o>
                      </l2>
                      <v n="Id">108L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCJump">
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Init"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">30L</v>
                          <v n="IdParent">29L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">31L</v>
                          <v n="IdParent">29L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">32L</v>
                          <v n="IdParent">29L</v>
                        </o>
                      </l2>
                      <v n="Id">29L</v>
                      <v n="IdParent">9L</v>
                    </o>
                  </l2>
                </o>
                <l2 n="Attributes" cet="SFCAttribute">
                  <o>
                    <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                    <o n="Value" t="StringValue">
                      <v n="Value">""</v>
                      <v n="DefaultValue">""</v>
                    </o>
                    <v n="Id">71L</v>
                    <v n="IdParent">9L</v>
                  </o>
                  <o>
                    <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                    <o n="Value" t="StringValue">
                      <v n="Value">""</v>
                      <v n="DefaultValue">""</v>
                    </o>
                    <v n="Id">72L</v>
                    <v n="IdParent">9L</v>
                  </o>
                  <o>
                    <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                    <o n="Value" t="BoolValue">
                      <v n="Value">"FALSE"</v>
                      <v n="DefaultValue">"FALSE"</v>
                    </o>
                    <v n="Id">73L</v>
                    <v n="IdParent">9L</v>
                  </o>
                </l2>
                <v n="Id">9L</v>
                <v n="IdParent">-1L</v>
              </o>
              <d2 n="Categories" ckt="Guid" cvt="SFCAttributeCategory">
                <v>1c5c6e05-2bb7-4258-bcee-fd16a540c63c</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Identifier">"Specific"</v>
                  <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="Description">"属性型固有プロパティ"</v>
                </o>
                <v>20f0fc67-978d-438b-979f-eef294f34ee4</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Identifier">"Actions"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"アクション定義"</v>
                </o>
                <v>6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Identifier">"Common"</v>
                  <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="Description">"共通プロパティ"</v>
                </o>
                <v>d336ba06-8a67-4e6b-9697-50f83ba6bdde</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Identifier">"Times"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"時間定義"</v>
                </o>
              </d2>
              <d2 n="Attributes" ckt="Guid" cvt="SFCAttributeDescription">
                <v>01580b27-6378-448b-8ecb-0e4b795b58d6</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">true</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                  <v n="Identifier">"Exclude"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"この要素をビルドから除外"</v>
                </o>
                <v>23bdaa98-72ec-41f7-817b-9dede5697086</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                  <v n="Identifier">"Parallel"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"分岐を並列モードに設定します"</v>
                </o>
                <v>38391c6d-6d4a-42f8-8ee7-9f45e5adafa8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                  <v n="Identifier">"Name"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"要素名"</v>
                </o>
                <v>62e1754b-7629-4e63-9cec-10ae0c536f1f</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                  <v n="Identifier">"Duplication"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"ステップ アクションまたは要素のある遷移の実装をコピーします。そうでない場合、参照を既存の実装にコピーします。"</v>
                </o>
                <v>6844a48e-46c2-4cc8-a185-a478f3b99cc0</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                  <v n="Identifier">"InitStep"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"初期ステップとしてステップを設定します"</v>
                </o>
                <v>700a583f-b4d4-43e4-8c14-629c7cd3bec8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                  <v n="Identifier">"MainAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"ステップがアクティブの場合に呼び出されるアクション名"</v>
                </o>
                <v>7d894980-aeea-405c-a0f6-e2b26429c58f</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">true</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                  <v n="Identifier">"Comment"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"要素のコメント"</v>
                </o>
                <v>8294df19-5962-4dee-a874-1051dabb0e3e</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                  <v n="Identifier">"Monitoring"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"トランジション監視設定を示しています。"</v>
                </o>
                <v>a2621e18-7de3-4ea6-ae6d-89e9e0b7befd</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                  <v n="Identifier">"ExitAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"ステップが非アクティブの場合に呼び出されるアクション名"</v>
                </o>
                <v>a6b08bd8-b696-47e3-9cbf-7408b61c9ff8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                  <v n="Identifier">"EntryAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"ステップがアクティブの場合に呼び出されるアクション名"</v>
                </o>
                <v>b693554c-1b01-4a8d-afde-9e3a46f7465d</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                  <v n="Identifier">"MaxTime"</v>
                  <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Description">"最大アクティブ時間をステップに定義します"</v>
                </o>
                <v>bc882c11-1e91-4dd8-a6b8-2075724ed18b</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                  <v n="Identifier">"Symbol"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"要素のシンボル コンフィグレーション設定"</v>
                </o>
                <v>cacf1a68-236e-47c2-b7b1-1cf9199718cb</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                  <v n="Identifier">"MinTime"</v>
                  <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Description">"最小アクティブ時間をステップに定義します"</v>
                </o>
                <v>e174fc0d-80b0-4a9e-a530-ca239c249a50</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                  <v n="Identifier">"Qualifier"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"アクション関連付けの修飾子"</v>
                </o>
              </d2>
              <d2 n="EnumTemplates" ckt="Guid" cvt="EnumValueTemplate">
                <v>6ecff51c-9b8f-4338-aab0-67c2b31b07e9</v>
                <o>
                  <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                  <l n="Values" t="ArrayList" cet="EnumEntry">
                    <o>
                      <v n="Identifier">"None"</v>
                      <v n="Value">0L</v>
                      <v n="Key">"None"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Variable"</v>
                      <v n="Value">1L</v>
                      <v n="Key">"Variable"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Call"</v>
                      <v n="Value">2L</v>
                      <v n="Key">"Call"</v>
                    </o>
                  </l>
                  <v n="BaseType">"INT"</v>
                </o>
                <v>79a4fdd5-c859-4de4-aa8d-c03372c880c2</v>
                <o>
                  <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                  <l n="Values" t="ArrayList" cet="EnumEntry">
                    <o>
                      <v n="Identifier">"Unspecified"</v>
                      <v n="Value">0L</v>
                      <v n="Key">"Unspecified"</v>
                    </o>
                    <o>
                      <v n="Identifier">"None"</v>
                      <v n="Value">1L</v>
                      <v n="Key">"None"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Read"</v>
                      <v n="Value">2L</v>
                      <v n="Key">"Read"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Write"</v>
                      <v n="Value">3L</v>
                      <v n="Key">"Write"</v>
                    </o>
                    <o>
                      <v n="Identifier">"ReadWrite"</v>
                      <v n="Value">4L</v>
                      <v n="Key">"ReadWrite"</v>
                    </o>
                  </l>
                  <v n="BaseType">"INT"</v>
                </o>
              </d2>
            </o>
          </Data>
          <TypeList>
            <Type n="ArrayList">System.Collections.ArrayList</Type>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoolValue">{89e1c7bb-c9f8-4be3-b8a7-019cdbb9f7e8}</Type>
            <Type n="EnumEntry">{4185e6da-1717-44c9-b705-102861764479}</Type>
            <Type n="EnumValue">{4dd7572b-4b9d-4d35-963e-6a34a4aaa5c1}</Type>
            <Type n="EnumValueTemplate">{d6bfe4f0-d62f-4b5f-9f95-2bbeb1950e28}</Type>
            <Type n="Guid">System.Guid</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="SFCAttribute">{21f3f16e-04fa-4637-b6b7-d84e4192e99f}</Type>
            <Type n="SFCAttributeCategory">{679adacf-f2a4-4167-a3f7-d21cfc5d451f}</Type>
            <Type n="SFCAttributeDescription">{d851789d-af2c-4990-9d48-a7bdc9181773}</Type>
            <Type n="SFCBranch">{e221b778-bb8f-44ba-8a6a-f796287d4e62}</Type>
            <Type n="SFCElementList">{587d6556-cfe6-4e76-9cc9-fc0daf0c8c29}</Type>
            <Type n="SFCImplementationObject">{74f81948-1328-492c-b6c1-a9ea72048b28}</Type>
            <Type n="SFCJump">{7e39ac27-154f-419a-a255-6a6cf37d5ed0}</Type>
            <Type n="SFCSegment">{f1db7f6f-4774-46a6-ad9b-a94414f875fc}</Type>
            <Type n="SFCStep">{86ee92a2-d863-4136-be27-82b36d84211c}</Type>
            <Type n="SFCTransition">{4ecb29e8-a90a-4646-84ac-2ff54215ab29}</Type>
            <Type n="String">System.String</Type>
            <Type n="StringValue">{778c8bac-3fa0-41e1-99d3-2b628d12d3e5}</Type>
          </TypeList>
        </XmlArchive>
      </SFC>
    </Implementation>
    <Action Name="autoRun_active" Id="{6e20425c-d870-46e8-8c79-c42919ac8af5}">
      <Implementation>
        <ST><![CDATA[IF autoRun._x AND autoRun.x = FALSE THEN
	THIS^.fbi_lensTranport();
	THIS^.fbi_lensTranport.p_Init := TRUE;
	THIS^.fbi_palletizeing();
	THIS^.fbi_palletizeing.p_Init := TRUE;
	THIS^.fbi_gm_measurementModule.SFCInit := TRUE;
	THIS^.fbi_gm_measurementModule();
	THIS^.fbi_gm_transport();
	THIS^.fbi_gm_transport.p_Init := TRUE;
ELSIF autoRun._x AND autoRun.x THEN
	THIS^.fbi_lensTranport();
	THIS^.fbi_lensTranport.p_Init := FALSE;
	THIS^.fbi_palletizeing();
	THIS^.fbi_palletizeing.p_Init := FALSE;
	IF gvl_visu.flg_btn_usingMeasurementSystem THEN
		THIS^.fbi_gm_measurementModule();
		THIS^.fbi_gm_measurementModule.SFCInit := FALSE;
		THIS^.fbi_gm_transport();
		THIS^.fbi_gm_transport.p_Init := FALSE;
	END_IF
	fbi_dataSampling(
	in_flg_run:= gvl_auto.flg_dataSampling_run, 
	in_var_cavNo:= gvl_auto.buf_cavNo, 
	in_var_pocketNo:= gvl_auto.pocketNo[gvl_auto.buf_cavNo], 
	in_var_gateLength:= gvl_auto.buf_gateLength, 
	in_var_date:= gvl_visu.var_DT, 
	in_flg_nonDefective:= gvl_auto.flg_DataSample_nonDefective, 
	in_flg_defective:= gvl_auto.flg_DataSample_defective, 
	in_flg_sample:= gvl_auto.flg_DataSamle_sample, 
	in_flg_reset:= , 
	ref_dataSet:= gvl_auto.var_DataSet);

	fbi_gateLengthList();
	
	fbi_debuger(
	in_flg_run:= gvl_debug.flg_debug_run, 
	in_flg_start:= gvl_debug.flg_debug_run, 
	in_var_cavQty:= gvl_param.var_productInfo[gvl_param.var_currentProductID].cavQty, 
	out_flg_gateLengthISSuccessed=> gvl_debug.flg_passingMeasurement, 
	out_flg_dummySignal=> , 
	out_flg_lensSetDone=> gvl_debug.out_lensSetDone, 
	out_flg_fiberSens=> gvl_debug.out_fiberSens, 
	out_flg_busy=> gvl_debug.out_busy, 
	out_cav=> gvl_debug.var_cav);
	
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="measurementSystemHome_active" Id="{1bb8f388-2672-415a-b6ef-d9bf552f8ea9}">
      <Implementation>
        <ST><![CDATA[IF measurementSystemHome._x AND measurementSystemHome.x = FALSE THEN
	trn_measurementSystemHomeDone := FALSE;
	gvl_auto.gm_rotaryPowerOn := FALSE;
	var_process := 0;
ELSIF measurementSystemHome._x AND measurementSystemHome.x THEN
	IF gvl_visu.flg_btn_usingMeasurementSystem THEN
		CASE var_process OF
			0://insert parameter
				gvl_solv.fbi_gm_ejector.in_flg_run := FALSE;
				gvl_solv.fbi_gm_chuck.in_flg_run := FALSE;
				gvl_solv.fbi_gm_push.in_flg_run := FALSE;
				gvl_solv.fbi_gm_pickup.in_flg_run := FALSE;
				gvl_solv.fbi_gm_rotary.in_flg_run := FALSE;
				gvl_solv.fbi_gm_stamp.in_flg_run := FALSE;
				gvl_elecylinder.fbi_gm_axisPickUp.in_flg_run := FALSE;
				gvl_elecylinder.fbi_gm_axisTransport.in_flg_run := FALSE;
				gvl_solv.fbi_gm_ejector.in_var_vacMode := eP_ejeVacMode.halt;
				gvl_solv.fbi_gm_chuck.in_var_moveMode := eP_svMoveMode.svA;
				gvl_solv.fbi_gm_push.in_var_moveMode := eP_svMoveMode.svA;
				gvl_solv.fbi_gm_pickup.in_var_moveMode := eP_svMoveMode.svA;
				gvl_solv.fbi_gm_rotary.in_var_moveMode := eP_svMoveMode.svA;
				gvl_solv.fbi_gm_stamp.in_var_moveMode := eP_svMoveMode.svA;
				gvl_elecylinder.fbi_gm_axisPickUp.in_var_moveMode := eP_eleMoveMode.eleA;
				gvl_elecylinder.fbi_gm_axisTransport.in_var_moveMode := eP_eleMoveMode.eleA;
				gvl_axis.ref_r.Position := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.gm_rotary.origin;
				gvl_auto.gm_rotaryPowerOn := TRUE;
				IF gvl_axis.fbi_mc_powerR.Status THEN
					var_process := 1;
				END_IF
			1://first move
				gvl_solv.fbi_gm_ejector.in_flg_run := TRUE;
				gvl_solv.fbi_gm_chuck.in_flg_run := TRUE;
				gvl_solv.fbi_gm_push.in_flg_run := TRUE;
				gvl_elecylinder.fbi_gm_axisPickUp.in_flg_run := TRUE;
				gvl_elecylinder.fbi_gm_axisTransport.in_flg_run := TRUE;
				IF gvl_solv.ref_gm_chuck.in.in_flg_sensA AND
				   gvl_solv.ref_gm_push.in.in_flg_sensA AND
				   gvl_elecylinder.ref_gm_axisPickUp.input.in_flg_sensA AND 
				   gvl_elecylinder.ref_gm_axisTransport.input.in_flg_sensA THEN
				   	gvl_solv.fbi_gm_ejector.in_flg_run := FALSE;
					gvl_solv.fbi_gm_chuck.in_flg_run := FALSE;
					gvl_solv.fbi_gm_push.in_flg_run := FALSE;
					gvl_elecylinder.fbi_gm_axisPickUp .in_flg_run := FALSE;
					gvl_elecylinder.fbi_gm_axisTransport.in_flg_run := FALSE;
					var_process := 2;
				END_IF
			2://second move	
				gvl_axis.ref_r.Execute := TRUE;
				IF gvl_axis.ref_r.Done THEN
					gvl_axis.ref_r.Execute := FALSE;
					var_process := 3;
				END_IF
			3://third move
				gvl_solv.fbi_gm_pickup.in_flg_run := TRUE;
				gvl_solv.fbi_gm_rotary.in_flg_run := TRUE;
				gvl_solv.fbi_gm_stamp.in_flg_run := TRUE;
				IF gvl_solv.ref_gm_pickUp.in.in_flg_sensA AND gvl_solv.ref_gm_rotary.in.in_flg_sensA AND gvl_solv.ref_gm_stamp.in.in_flg_sensA THEN
					var_process := 4;
				END_IF
			4:	
				trn_measurementSystemHomeDone := TRUE;
		END_CASE
		IF gvl_axis.ref_r.Error THEN
			gvl_axis.ref_r.Execute := false;
			var_process := 100;
		END_IF
	ELSE
		trn_measurementSystemHomeDone := TRUE;
	END_IF
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="moveToHome_active" Id="{16d02ed0-296b-4321-886b-30e2802ea8ea}">
      <Implementation>
        <ST><![CDATA[IF moveToHome._x AND moveToHome.x = FALSE THEN
	var_process := 0;
	trn_moveToHomeDone := FALSE;
	gvl_auto.motorPowerOn := FALSE;
ELSIF moveToHome._x AND moveToHome.x THEN
	CASE var_process OF
		0:
			gvl_auto.motorPowerOn := TRUE;
			IF gvl_axis.flg_motorReady THEN
				var_process := 1;
			END_IF
		1://move axisZ
			gvl_axis.ref_z.Position := 0;
			gvl_axis.ref_z.Execute := TRUE;
			IF gvl_axis.ref_z.Done THEN
				gvl_axis.ref_z.Execute := FALSE;
				var_process := 2;
			END_IF
		2://insert parameter
			gvl_solv.fbi_push.in_flg_run := FALSE;
			gvl_elecylinder.fbi_axisTransport.in_var_moveMode := eP_eleMoveMode.eleA;
			gvl_elecylinder.fbi_axisSample.in_var_moveMode := eP_eleMoveMode.eleA;
			gvl_elecylinder.fbi_axisRotary.in_var_moveMode := eP_eleMoveMode.eleA;
			gvl_solv.fbi_chuck.in_var_moveMode := eP_svMoveMode.svA;
			gvl_solv.fbi_push.in_var_moveMode := eP_svMoveMode.svA;
			gvl_elecylinder.fbi_axisTransport.in_flg_run := FALSE;
			gvl_elecylinder.fbi_axisSample.in_flg_run := FALSE;
			gvl_elecylinder.fbi_axisRotary.in_flg_run := FALSE;
			gvl_solv.fbi_chuck.in_flg_run := FALSE;
			gvl_solv.fbi_push.in_flg_run := FALSE;
			gvl_axis.fbi_motionControler.in_flg_start := false;
			gvl_axis.fbi_motionControler.in_var_targetPosX := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.initial.x;
			gvl_axis.fbi_motionControler.in_var_targetPosY := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.initial.y;
			gvl_axis.fbi_motionControler.in_var_targetPosZ := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.initial.z;
			gvl_axis.fbi_motionControler.in_var_direction := eP_motionDirection.XYZ;
			var_process := 3;
		3://moving start
			gvl_elecylinder.fbi_axisTransport.in_flg_run := TRUE;
			gvl_elecylinder.fbi_axisSample.in_flg_run := TRUE;
			gvl_elecylinder.fbi_axisRotary.in_flg_run := TRUE;
			gvl_solv.fbi_chuck.in_flg_run := TRUE;
			gvl_solv.fbi_push.in_flg_run := TRUE;
			gvl_axis.fbi_motionControler.in_flg_start := TRUE;
			IF gvl_elecylinder.fbi_axisTransport.out_flg_Done THEN
				flg_tranHomeDone := TRUE;
			END_IF
			IF gvl_elecylinder.fbi_axisSample.out_flg_Done THEN
				flg_sampleHomeDone := TRUE;
			END_IF
			IF gvl_elecylinder.fbi_axisRotary.out_flg_Done THEN
				flg_rotaryHomeDone := TRUE;
			END_IF
			IF gvl_solv.fbi_chuck.out_flg_Done THEN
				flg_chuckHomeDone := TRUE;
			END_IF
			IF gvl_solv.fbi_push.out_flg_Done THEN
				flg_pushHomeDone := TRUE;
			END_IF
			IF gvl_axis.fbi_motionControler.out_flg_Done THEN
				flg_axisHomeDone := TRUE;
			END_IF 
			IF flg_tranHomeDone AND flg_sampleHomeDone AND flg_chuckHomeDone AND flg_axisHomeDone AND flg_pushHomeDone AND flg_rotaryHomeDone THEN
				var_process := 4;
			END_IF
		4://clear flag
			flg_tranHomeDone := FALSE;
			flg_sampleHomeDone := FALSE;
			flg_chuckHomeDone := FALSE;
			flg_pushHomeDone := FALSE;
			flg_axisHomeDone := FALSE;
			flg_rotaryHomeDone := FALSE;
			gvl_elecylinder.fbi_axisTransport.in_flg_run := FALSE;
			gvl_elecylinder.fbi_axisSample.in_flg_run := FALSE;
			gvl_elecylinder.fbi_axisTrayChange.in_flg_run := FALSE;
			gvl_elecylinder.fbi_axisRotary.in_flg_run := FALSE;
			gvl_solv.fbi_chuck.in_flg_run := FALSE;
			gvl_solv.fbi_push.in_flg_run := FALSE;
			gvl_axis.fbi_motionControler.in_flg_start := FALSE;
			var_process := 5;
		5://check position
			trn_moveToHomeDone := TRUE;			
	END_CASE
END_IF]]></ST>
      </Implementation>
    </Action>
    <Property Name="p_Init" Id="{c2d0da88-466b-4d96-8bc5-090a73b1a683}">
      <Declaration><![CDATA[PROPERTY p_Init : BOOL]]></Declaration>
      <Get Name="Get" Id="{049645de-0c21-46cb-b025-7b12ce1ac435}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[p_Init := THIS^.SFCInit;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{a7055906-8822-44fe-844c-79624dc22269}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[THIS^.SFCInit := p_Init;]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Action Name="paramInit_active" Id="{3554c9c6-7cc2-4335-ba5f-a6a21c001791}">
      <Implementation>
        <ST><![CDATA[IF paramInit._x AND paramInit.x = FALSE THEN
	trn_paramInitDone := FALSE;
	fbi_paramInit.in_flg_run := FALSE;
	THIS^.fbi_lensTranport.p_Init := TRUE;
	THIS^.fbi_lensTranport();
	THIS^.fbi_palletizeing.p_Init := TRUE;
	THIS^.fbi_palletizeing();
	THIS^.fbi_gm_measurementModule.SFCInit := TRUE;
	THIS^.fbi_gm_measurementModule();
	THIS^.fbi_gm_transport();
	THIS^.fbi_gm_transport.p_Init := TRUE;
ELSIF paramInit._x AND paramInit.x THEN
	gvl_auto.gateLengthIsPassed := FALSE;
	gvl_auto.pickUpLnesDone := FALSE;
	gvl_auto.lensVacuumDone := FALSE;
	gvl_auto.requirementToPickUpLens := FALSE;
	gvl_gm.flg_requestPickup := FALSE;
	gvl_gm.flg_lensSetDoneFromGM := FALSE;
	gvl_gm.flg_lensRequest := FALSE;
	gvl_gm.flg_lensPickUpDone := FALSE;
	gvl_debug.flg_debug_run := FALSE;
	gvl_debug.flg_stampDone :=FALSE;
	gvl_debug.flg_stampReady := FALSE;
	gvl_debug.flg_check_quality:= FALSE;
	gvl_debug.flg_to_measurement:= FALSE;
	gvl_debug.flg_to_stocker:= FALSE;
	gvl_visu.flg_btn_vacSensOn := FALSE;
	gvl_visu.flg_btn_gm_motorPower := FALSE;
	gvl_visu.flg_btn_buzzer_silent := FALSE;
	gvl_visu.flg_powerOn := FALSE;
	fbi_paramInit.in_flg_run := TRUE;
	IF fbi_paramInit.out_flg_done THEN
		fbi_paramInit.in_flg_run := FALSE;
		trn_paramInitDone := TRUE;
	END_IF
END_IF

fbi_paramInit(in_flg_run:= , out_flg_done=> );]]></ST>
      </Implementation>
    </Action>
    <Action Name="removeLens_active" Id="{c740f2c1-662e-4a4b-82ef-bf592dd0c6fd}">
      <Implementation>
        <ST><![CDATA[IF removeLens._x AND removeLens.x = FALSE THEN
	timer.IN := FALSE;
	timer2.IN := FALSE;
	trn_removeLensDone := FALSE;
	var_process := 0;
ELSIF removeLens._x AND removeLens.x THEN
	CASE var_process OF
		0://insert parameter
			fbi_gm_removeLens.p_Init := TRUE;
			gvl_axis.fbi_motionControler.in_var_targetPosX := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.remove.x;
			gvl_axis.fbi_motionControler.in_var_targetPosY := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.remove.y;
			gvl_axis.fbi_motionControler.in_var_targetPosZ := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.remove.z;
			gvl_axis.fbi_motionControler.in_var_direction := eP_motionDirection.XYZ;
			IF gvl_solv.ref_ejector.input.in_flg_sensVac THEN
				var_process := 1;
			ELSE
				gvl_solv.fbi_ejector.in_var_vacMode := eP_ejeVacMode.break;
				gvl_solv.fbi_ejector.in_flg_run := TRUE;
				var_process := 20;
			END_IF
		1://move start
			gvl_axis.fbi_motionControler.in_flg_start := TRUE;
			IF gvl_axis.fbi_motionControler.out_flg_Done THEN
				var_process := 2;
			END_IF
		2://insert ejector parameter
			gvl_axis.fbi_motionControler.in_flg_start := FALSE;
			gvl_solv.fbi_ejector.in_flg_run := FALSE;
			gvl_solv.fbi_ejector.in_var_vacMode := eP_ejeVacMode.break;
			var_process := 3;
		3://break
			gvl_solv.fbi_ejector.in_flg_run := TRUE;
			IF gvl_solv.fbi_ejector.out_flg_Done THEN
				gvl_solv.fbi_ejector.in_flg_run := FALSE;
				var_process := 4;
			END_IF
		4://insert initial position
			gvl_solv.fbi_ejector.in_flg_run := FALSE;
			gvl_solv.fbi_chuck.in_var_moveMode := eP_svMoveMode.svA;
			gvl_axis.fbi_motionControler.in_var_targetPosX := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.initial.x;
			gvl_axis.fbi_motionControler.in_var_targetPosY := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.initial.y;
			gvl_axis.fbi_motionControler.in_var_targetPosZ := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.initial.z;
			gvl_axis.fbi_motionControler.in_var_direction := eP_motionDirection.ZYX;
			var_process := 5;
		5://move to initial position
			gvl_axis.fbi_motionControler.in_flg_start := TRUE;
			IF gvl_axis.fbi_motionControler.out_flg_Done THEN
				gvl_solv.fbi_gm_push.in_flg_run := FALSE;
				gvl_solv.fbi_gm_chuck.in_flg_run := FALSE;
				IF gvl_io.flg_fiberSens THEN
					var_process := 6;
				ELSE
					var_process := 20;
				END_IF
			END_IF
		6:
			gvl_solv.fbi_chuck.in_var_moveMode := eP_svMoveMode.svB;
			gvl_solv.fbi_push.in_var_moveMode := eP_svMoveMode.svB;
			gvl_elecylinder.fbi_axisTransport.in_var_moveMode := eP_eleMoveMode.eleB;
			gvl_solv.fbi_ejector.in_var_vacMode := eP_ejeVacMode.halt;
			gvl_axis.fbi_motionControler.in_var_targetPosX := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.pickUp.x;
			gvl_axis.fbi_motionControler.in_var_targetPosY := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.pickUp.y;
			gvl_axis.fbi_motionControler.in_var_targetPosZ := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.pickUp.z;
			gvl_axis.fbi_motionControler.in_var_direction := eP_motionDirection.XYZ;
			var_process := 7;
		7:
			gvl_elecylinder.fbi_axisTransport.in_flg_run := TRUE;
			gvl_solv.fbi_ejector.in_flg_run := TRUE;
			gvl_solv.fbi_chuck.in_flg_run := TRUE;
			gvl_solv.fbi_push.in_flg_run := TRUE;
			var_process := 8;
		8:
			IF gvl_io.in_wire_svChuckClose AND gvl_io.in_wire_svPushClose AND gvl_io.in_flg_eleTransportMoving THEN
				gvl_axis.fbi_motionControler.in_flg_start := TRUE;
				gvl_solv.fbi_ejector.in_flg_run := FALSE;
				gvl_elecylinder.fbi_axisTransport.in_flg_run := FALSE;
				gvl_solv.fbi_chuck.in_flg_run := FALSE;
				gvl_solv.fbi_push.in_flg_run := FALSE;
				var_process := 9;
			END_IF
		9:
			IF gvl_axis.fbi_motionControler.out_flg_Done THEN
				gvl_axis.fbi_motionControler.in_flg_start := FALSE;
				gvl_axis.fbi_motionControler.in_var_targetPosX := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.initial.x;
				gvl_axis.fbi_motionControler.in_var_targetPosY := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.initial.y;
				gvl_axis.fbi_motionControler.in_var_targetPosZ := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.initial.z;
				gvl_axis.fbi_motionControler.in_var_direction := eP_motionDirection.ZYX;
				var_process := 10;
			END_IF
		10:
			gvl_axis.fbi_motionControler.in_flg_start := TRUE;
			var_process := 11;
		11:
			IF gvl_axis.fbi_motionControler.out_flg_Done THEN
				gvl_axis.fbi_motionControler.in_flg_start := FALSE;
				gvl_axis.fbi_motionControler.in_var_targetPosX := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.remove.x;
				gvl_axis.fbi_motionControler.in_var_targetPosY := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.remove.y;
				gvl_axis.fbi_motionControler.in_var_targetPosZ := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.remove.z;
				gvl_axis.fbi_motionControler.in_var_direction := eP_motionDirection.XYZ;
				var_process := 12;
			END_IF
		12:
			gvl_axis.fbi_motionControler.in_flg_start := TRUE;
			gvl_solv.fbi_ejector.in_var_vacMode := eP_ejeVacMode.break;
			var_process := 13;
		13:
			IF gvl_axis.fbi_motionControler.out_flg_Done THEN
				gvl_solv.fbi_ejector.in_flg_run := TRUE;
				var_process := 14;	
			END_IF
		14:
			IF gvl_solv.fbi_ejector.out_flg_Done THEN
				gvl_solv.fbi_ejector.in_flg_run := FALSE;
				gvl_axis.fbi_motionControler.in_var_targetPosX := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.initial.x;
				gvl_axis.fbi_motionControler.in_var_targetPosY := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.initial.y;
				gvl_axis.fbi_motionControler.in_var_targetPosZ := gvl_param.var_productInfo[gvl_param.var_currentProductID].teachPos.initial.z;
				gvl_axis.fbi_motionControler.in_var_direction := eP_motionDirection.ZYX;
				var_process := 15;	
			END_IF
		15:
			gvl_axis.fbi_motionControler.in_flg_start := TRUE;
			gvl_solv.fbi_chuck.in_var_moveMode := eP_svMoveMode.svB;
			gvl_solv.fbi_push.in_var_moveMode := eP_svMoveMode.svB;
			gvl_elecylinder.fbi_axisTransport.in_var_moveMode := eP_eleMoveMode.eleB;
			var_process := 16;
		16:
			IF gvl_axis.fbi_motionControler.out_flg_Done THEN
				IF gvl_axis.fbi_motionControler.out_flg_Done THEN
					gvl_elecylinder.fbi_axisTransport.in_flg_run := TRUE;
					gvl_solv.fbi_chuck.in_flg_run := TRUE;
					gvl_solv.fbi_push.in_flg_run := TRUE;
					var_process := 17;
				END_IF
			END_IF
		17:
			IF gvl_io.in_wire_svChuckOpen AND gvl_io.in_wire_svPushOpen AND gvl_io.in_flg_eleTransportOrigin THEN
				gvl_elecylinder.fbi_axisTransport.in_flg_run := FALSE;
				gvl_solv.fbi_chuck.in_flg_run := FALSE;
				gvl_solv.fbi_push.in_flg_run := FALSE;
				var_process := 20;
			END_IF
		20:
			IF NOT gvl_visu.flg_btn_usingMeasurementSystem THEN
				var_process := 50;
			ELSE
				fbi_gm_removeLens.p_Init := TRUE;
				fbi_gm_removeLens.in_flg_run := FALSE;
				var_process := 21;
			END_IF
		21:
			fbi_gm_removeLens.p_Init := FALSE;
			fbi_gm_removeLens.in_flg_run := TRUE;
			var_process := 22;
		22:
			fbi_gm_removeLens.in_flg_run := FALSE;
			IF fbi_gm_removeLens.out_flg_Done THEN
				var_process := 50;
			END_IF
			
		50:
			gvl_solv.fbi_ejector.in_flg_run := FALSE;
			trn_removeLensDone := TRUE;
	END_CASE
	fbi_gm_removeLens(in_flg_run:= , out_flg_Done=> );
	timer(IN:= , PT:= T#0.5S , Q=> , ET=> );
	timer2(IN:= , PT:= T#0.5S , Q=> , ET=> );
END_IF]]></ST>
      </Implementation>
    </Action>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="SFCProperty">
            <n n="SFCErrorAnalyzation" />
            <n n="SFCErrorAnalyzationTable" />
            <v n="Title">"IecSfc"</v>
            <v n="Company">"System"</v>
            <v n="Version">"3.4.2.0"</v>
            <v n="Namespace">""</v>
            <d2 n="Flags" ckt="Flags" cvt="SFCPropertyFlagData">
              <v>EnableLimit</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Init</v>
              <o>
                <v n="Use">true</v>
                <v n="Declare">true</v>
              </o>
              <v>Reset</v>
              <o>
                <v n="Use">true</v>
                <v n="Declare">true</v>
              </o>
              <v>QuitError</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Pause</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Error</v>
              <o>
                <v n="Use">true</v>
                <v n="Declare">true</v>
              </o>
              <v>Trans</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>ErrorStep</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>ErrorPOU</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>CurrentStep</v>
              <o>
                <v n="Use">true</v>
                <v n="Declare">true</v>
              </o>
              <v>Tip</v>
              <o>
                <v n="Use">true</v>
                <v n="Declare">true</v>
              </o>
              <v>TipMode</v>
              <o>
                <v n="Use">true</v>
                <v n="Declare">true</v>
              </o>
              <v>SFCErrorAnalyzation</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>SFCErrorAnalyzationTable</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
            </d2>
            <v n="CalcActiveTransOnly">false</v>
            <v n="UseDefaults">true</v>
          </o>
        </Data>
        <TypeList>
          <Type n="Boolean">System.Boolean</Type>
          <Type n="Flags">{27d8150b-ef58-4fff-8da1-1f7dd5f9ea51}</Type>
          <Type n="SFCProperty">{58548d2c-f1b1-453d-9195-66c94e2a3ae0}</Type>
          <Type n="SFCPropertyFlagData">{24565a38-6368-4874-ab9a-0ef7ec269521}</Type>
          <Type n="String">System.String</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
    <LineIds Name="fb_auto.autoRun_active">
      <LineId Id="2" Count="44" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="fb_auto.measurementSystemHome_active">
      <LineId Id="2" Count="68" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="fb_auto.moveToHome_active">
      <LineId Id="2" Count="46" />
      <LineId Id="86" Count="0" />
      <LineId Id="50" Count="33" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="fb_auto.p_Init.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="fb_auto.p_Init.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="fb_auto.paramInit_active">
      <LineId Id="2" Count="36" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="fb_auto.removeLens_active">
      <LineId Id="2" Count="165" />
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>