<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{c726c6cb-38f1-459f-90ce-2fd1cbc12234}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbi_lsm_main: fb_lsm_main;
	fbi_text_control_run: fb_text_control;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbi_lsm_main();
fbi_text_control_run();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>